### PR TITLE
Fixed Deprecated Method Issue Across Multiple Measures

### LINKED ISSUE #140: Handle OpenStudio v3.7.0 deprecated methods
There are a couple measures that call deprecated methods 
`openstudio::model::AirLoopHVACUnitarySystem::setSupplyAirFlowRateMethodDuringCoolingOperation` and `openstudio::model::AirLoopHVACUnitarySystem::setSupplyAirFlowRateMethodDuringHeatingOperation`. 

E.g.: 
https://github.com/NREL/ComStock/blob/71597058f9077c77d3c3fc6ae2d38c1c91e74034/resources/measures/hardsize_model/measure.rb#L142-L143
and
https://github.com/NREL/ComStock/blob/71597058f9077c77d3c3fc6ae2d38c1c91e74034/resources/measures/upgrade_hvac_doas_hp_minisplits/measure.rb#L1353-L1360

Example of how to handle these: 
https://github.com/NREL/ComStock/blob/71597058f9077c77d3c3fc6ae2d38c1c91e74034/resources/measures/upgrade_hvac_console_gshp/measure.rb#L414-L422

Might want to also check for [any others](https://github.com/NREL/OpenStudio/blob/02cf3b838a352eb17c33a78cb8773f478029b318/developer/ruby/deprecated_methods.csv).

### PR DESCRIPTION
**Pull request by LandanT**
Utilized the recommended fix by Eric to solve the OS Version 3.7.0 unitary system deprecated method issue. This fixed applied to 5 measures. There are also some formatting fixes that took place to remove trailing white spaces and some rubocop finds.

Pull request overview
---------------------

 - Fixes #140 

### Pull Request Author

This pull request makes changes to (select all the apply):
 - [ ] Documentation
 - [ ] Infrastructure (includes singularity image, buildstock batch, dependencies, continuous integration tests)
 - [ ] Sampling
 - [ ] Workflow Measures
 - [x] Upgrade Measures
 - [ ] Reporting Measures
 - [ ] Postprocessing

Author pull request checklist:

 - [x] Tagged the pull request with the appropriate label (documentation, infrastructure, sampling, workflow measure, upgrade measure, reporting measure, postprocessing) to help categorize changes in the release notes.
 - [ ] Added tests for new measures
 - [x] Updated measure .xml(s)
 - [ ] Register values added to `comstock_column_definitions.csv`
 - [ ] Both `options_lookup.tsv` files updated
 - [ ] 10k+ test run
 - [ ] Change documentation written
 - [ ] Measure documentation written
 - [ ] ComStock documentation updated
 - [ ] Changes reflected in example `.yml` files
 - [ ] Changes reflected in `README.md` files
 - [ ] Added 'See ComStock License' language to first two lines of each code file
 - [ ] Implements corresponding measure tests and indexing path in `test/measure_tests.txt` or/and `test/resource_measure_tests.txt`
 - [ ] All new and existing tests pass the CI

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a code review on GitHub
 - [ ] All related changes have been implemented: data and method additions, changes, tests
 - [ ] If fixing a defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] Reviewed change documentation
 - [ ] Ensured code files contain License reference
 - [ ] Results differences are reasonable
 - [ ] Make sure the newly added measures has been added with tests and indexed properly
 - [ ] CI status: all tests pass

#### ComStock Licensing Language - Add to Beginning of Each Code File
```
# ComStock™, Copyright (c) 2023 Alliance for Sustainable Energy, LLC. All rights reserved.
# See top level LICENSE.txt file for license terms.
```

### CODE REVIEW

File: resources/measures/upgrade_hvac_add_heat_pump_rtu/measure.rb [hunk 1]
```diff
@@ -1989,17 +1989,25 @@ def run(model, runner, user_arguments)
...
+        # set heating design flow rate
+        new_air_to_air_heatpump.setSupplyAirFlowRateDuringHeatingOperation(hash_htg_airflow_stgs[4])
+        # set no load design flow rate
+        new_air_to_air_heatpump.resetSupplyAirFlowRateMethodWhenNoCoolingorHeatingisRequired
+        new_air_to_air_heatpump.setSupplyAirFlowRateWhenNoCoolingorHeatingisRequired(min_airflow_m3_per_s)
+      else
+        new_air_to_air_heatpump.autosizeSupplyAirFlowRateDuringCoolingOperation
+        new_air_to_air_heatpump.autosizeSupplyAirFlowRateDuringHeatingOperation
+        new_air_to_air_heatpump.autosizeSupplyAirFlowRateWhenNoCoolingorHeatingisRequired
+      end
```
Comment (eringold) [inline resources/measures/upgrade_hvac_add_heat_pump_rtu/measure.rb]: I don't think these are correct changes. Originally the measure was setting the flow rates, and this will change that behavior to autosize the flow rates. Only `resetSupplyAirFlowRateWhenNoCoolingorHeatingisRequired` is deprecated, but that doesn't seem necessary when the 'No Cooling or Heating' flow rate is set right after. Just remove the line with that method.

File: resources/measures/upgrade_hvac_doas_hp_minisplits/measure.rb [hunk 2]
```diff
@@ -1341,24 +1341,30 @@ def run(model, runner, user_arguments)
...
+        # set heating design flow rate
+        unitary_sys.setSupplyAirFlowRateMethodDuringHeatingOperation('SupplyAirFlowRate')
+        unitary_sys.setSupplyAirFlowRateDuringHeatingOperation(airflow_stage4)
+        # set no load design flow rate
+        unitary_sys.setSupplyAirFlowRateMethodWhenNoCoolingorHeatingisRequired('SupplyAirFlowRate')
+        unitary_sys.setSupplyAirFlowRateWhenNoCoolingorHeatingisRequired(airflow_stage1)
+      else
+        unitary_sys.autosizeSupplyAirFlowRateDuringCoolingOperation
+        unitary_sys.autosizeSupplyAirFlowRateDuringHeatingOperation
+        unitary_sys.autosizeSupplyAirFlowRateWhenNoCoolingorHeatingisRequired
```
Comment (eringold) [inline resources/measures/upgrade_hvac_doas_hp_minisplits/measure.rb]: Again this changes measure behavior. Keep the flow rate assignments, don't autosize

File: resources/measures/upgrade_hvac_replace_boiler_by_heatpump/measure.rb [hunk 3]
```diff
@@ -362,9 +362,16 @@ def run(model, runner, user_arguments)
...
-        runner.registerInfo("SupplyAirFlowRateMethodDuringHeatingOperation is resetted to use 'SupplyAirFlowRate' method")
+      if model.version < OpenStudio::VersionString.new('3.7.0')
+        if flowmethod == ''
+          unit.setSupplyAirFlowRateMethodDuringHeatingOperation('SupplyAirFlowRate')
+          runner.registerInfo("SupplyAirFlowRateMethodDuringHeatingOperation is reset to use 'SupplyAirFlowRate' method")
+        end
+      else
+        if flowmethod == ''
+          unit.autosizeSupplyAirFlowRateDuringHeatingOperation
+          runner.registerInfo("Utilized autosizeSupplyAirFlowRateMethodDuringHeatingOperation method")
```
Comment (eringold) [inline resources/measures/upgrade_hvac_replace_boiler_by_heatpump/measure.rb]: As of 3.7.0, the `[autosizeSupplyAirFlowRateDuringHeatingOperation](https://s3.amazonaws.com/openstudio-sdk-documentation/cpp/OpenStudio-3.7.0-doc/model/html/classopenstudio_1_1model_1_1_air_loop_h_v_a_c_unitary_system.html#a50cb4fa8134d6e77e500dc33fd6a806a)' method will will set the flow "[method](https://bigladdersoftware.com/epx/docs/23-2/input-output-reference/group-unitary-equipment.html#field-heating-supply-air-flow-rate-method-000)" to 'SupplyAirFlowRate', so the original info message is still correct and should be kept.

**Review by eringold — CHANGES_REQUESTED** [review]

File: resources/measures/upgrade_hvac_replace_boiler_by_heatpump/measure.rb (hunk 3 above)
Comment (LandanT) [reply resources/measures/upgrade_hvac_replace_boiler_by_heatpump/measure.rb]: Updated to use the original text

File: resources/measures/upgrade_hvac_doas_hp_minisplits/measure.rb (hunk 2 above)
Comment (LandanT) [reply resources/measures/upgrade_hvac_doas_hp_minisplits/measure.rb]: Oh my bad. Updated to still set the flow rates but with the new method

File: resources/measures/upgrade_hvac_add_heat_pump_rtu/measure.rb (hunk 1 above)
Comment (LandanT) [reply resources/measures/upgrade_hvac_add_heat_pump_rtu/measure.rb]: Good point I relized my error after going through these. Comments. I think I have it handled correctly now.

**Review by mdahlhausen — APPROVED** [review]

**Review by eringold — APPROVED** [review]
